# Generated by Django 5.0.7 on 2024-09-07 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Domaine', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Mention', models.CharField(max_length=50)),
                ('Domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='ginscription.domaine')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Niveau', models.CharField(max_length=50)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='ginscription.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Parcours', models.CharField(max_length=50, null=True)),
                ('Mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='ginscription.mention')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Datenaiss', models.DateField()),
                ('Lieunaiss', models.CharField(max_length=50)),
                ('Nationalite', models.CharField(max_length=10)),
                ('Cin', models.PositiveIntegerField(blank=True, null=True)),
                ('Date_cin', models.DateField(blank=True, null=True)),
                ('Lieu_cin', models.CharField(blank=True, max_length=50, null=True)),
                ('Nom_pere', models.CharField(blank=True, max_length=50, null=True)),
                ('Profession_pere', models.CharField(blank=True, max_length=50, null=True)),
                ('Nom_mere', models.CharField(blank=True, max_length=50, null=True)),
                ('Profession_mere', models.CharField(blank=True, max_length=50, null=True)),
                ('Nom_tuteur', models.CharField(blank=True, max_length=50, null=True)),
                ('Profession_tuteur', models.CharField(blank=True, max_length=50, null=True)),
                ('Telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('Adresse_parents', models.CharField(max_length=50)),
                ('Bacc_num_inscription', models.PositiveIntegerField()),
                ('Bacc_annee', models.DateField()),
                ('Bacc_serie', models.CharField(max_length=4)),
                ('Bacc_centre', models.CharField(max_length=50)),
                ('Bacc_secteur', models.CharField(max_length=50)),
                ('Sesion', models.CharField(max_length=50)),
                ('Date_inscription', models.DateField()),
                ('Niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='ginscription.niveau')),
                ('Parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='ginscription.parcours')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_semestre', models.CharField(max_length=50)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='ginscription.grade')),
            ],
        ),
    ]
